(function(){
"use strict";
const A=window.VDMApp,D=A.read("search",{}),T=window.VDMText,root=document.getElementById("app-body");
A.frame(A.brand.name,A.brand.description);document.querySelector(".app-mark").textContent=A.brand.icon||"";
const seedRecords=(D.records||[]).filter(x=>!x.availableWhen&&String(x.keywords||"").includes("藤崎千尋"));
const seed={id:"initial-history",query:"藤崎千尋",kind:"all",at:Date.now(),reason:"recovery",resultIds:seedRecords.map(x=>x.id),snapshot:seedRecords,worldVersion:0,pageVersion:0,suggestion:""};
const local=A.appState({view:"history",query:"",kind:"all",history:[{sessionId:seed.id,query:seed.query,kind:"all",at:seed.at,worldVersion:0,pageVersion:0}],sessions:[seed],sessionId:null,sequence:0});
const available=(item)=>{const has=id=>Boolean(A.state&&A.state.hasEvidence&&A.state.hasEvidence(id)),required=Array.isArray(item.availableWhen)?item.availableWhen:item.availableWhen?[item.availableWhen]:[],removed=Array.isArray(item.removedWhen)?item.removedWhen:item.removedWhen?[item.removedWhen]:[],protectedUnseen=Boolean(item.protectUntilSeen&&!has(item.protectUntilSeen));if(required.length&&protectedUnseen)return false;if(!required.every(has))return false;if(removed.some(has)&&!protectedUnseen)return false;return true;};
const versions=(item)=>{const list=item.versions||[item];return list.filter(available).at(-1)||item;};
const matches=(item,q)=>T.includesAll([item.title,item.snippet,item.path,item.keywords,item.intents].flat().join(" "),q);
function endingResults(query,results,state){const ending=state.ending,player=String(state.player?.displayName||"").trim(),asksPlayer=player&&T.includesAll(query,player),asksChihiro=T.includesAll(query,"藤崎千尋"),asksProgram=T.includesAll(query,"生活情報保護連携実証事業")||T.includesAll(query,"関係参照補正");if(!ending)return results;if(ending==="A"){if(asksPlayer)return[];if(asksChihiro)return[{id:"end-a-city",kind:"all",title:"藤崎千尋｜公開記録・再索引",snippet:"市資料室、大学目録、地域記事を同一人物の記録として再索引しました。",path:"公開索引 / 参照関係統合",route:"vdm://kirikawa-city/staff"},{id:"end-a-news",kind:"news",title:"記録訂正の検証資料を公開｜霧川ローカルニュース",snippet:"削除前後の資料と個人名を含む検証記録です。",path:"kirikawa-news / corrections",route:"vdm://kirikawa-news/corrections"},...results.filter(x=>!String(x.id).startsWith("end-")).slice(0,6)];}if(ending==="B"){if(asksChihiro||asksPlayer)return[];if(asksProgram)return[{id:"end-b-program",kind:"all",title:"生活情報保護連携実証事業・検証記録",snippet:"契約範囲、訂正履歴、運用上の問題を匿名資料として公開しています。",path:"公開記録 / 制度検証",route:"vdm://kirikawa-city/life-protection"},{id:"end-b-log",kind:"news",title:"公開情報更新の検証結果｜匿名版",snippet:"個人を横断する対応表を除き、発生した事実と再発防止策を掲載。",path:"kirikawa-news / corrections",route:"vdm://kirikawa-news/corrections"}];}if(ending==="C")return[];return results;}
function knownVocabulary(){const current=A.state?.get?.()||{},player=String(current.player?.displayName||"").trim();if(current.ending==="C")return player?[player]:[];const stateTerms=current.discoveredTerms||[],safe=D.safeVocabulary||D.initialHistory||D.discoveredTerms||[];return[...new Set([...safe,...stateTerms])];}
function suggestions(q){const known=knownVocabulary(),direct=known.filter(x=>T.includesAll(x,q)||T.includesAll(q,x)).slice(0,6),typo=window.VDMContentEngine.suggest(q,known);return[...new Set([...direct,...(typo?[typo]:[])])].slice(0,6);}
function persist(patch){Object.assign(local,patch);A.saveAppState(local);}
function shell(inner){root.innerHTML='<section class="search-shell">'+inner+'</section>';}
function search(q,kind,reason){q=String(q||"").trim();if(!q){renderHome();return;}kind=kind||local.kind||"all";const state=A.state?.get?.()||{},all=(D.records||[]).map(versions).filter(available),baseResults=all.filter(x=>(kind==="all"||x.kind===kind)&&matches(x,q)),results=endingResults(q,baseResults,state).filter(x=>kind==="all"||x.kind===kind),suggestion=window.VDMContentEngine.suggest(q,knownVocabulary());local.sequence=(Number(local.sequence)||0)+1;const session={id:"s"+Date.now().toString(36)+"-"+local.sequence.toString(36),query:q,kind,at:Date.now(),reason:reason||"search",resultIds:results.map(x=>x.id),snapshot:JSON.parse(JSON.stringify(results)),worldVersion:state.worldVersion??state.world?.version??state.schemaVersion??0,pageVersion:state.pageVersion??state.world?.pageVersion??0,suggestion};if(state.ending!=="C"){local.sessions=[session,...local.sessions].slice(0,20);const retained=new Set(local.sessions.map(x=>x.id));local.history=[{sessionId:session.id,query:q,kind,at:session.at,worldVersion:session.worldVersion,pageVersion:session.pageVersion},...local.history].filter((h,i,list)=>retained.has(h.sessionId)&&list.findIndex(x=>x.sessionId===h.sessionId)===i).slice(0,20);}persist({view:"results",query:q,kind,sessionId:state.ending==="C"?null:session.id});renderResults(results,suggestion,session);return session;}
function restoreSession(id){const session=local.sessions.find(x=>x.id===id);if(!session){renderView("history");return;}persist({view:"results",query:session.query,kind:session.kind,sessionId:session.id});renderResults(session.snapshot||[],session.suggestion||"",session);}
function searchBox(value){return '<form class="search-box" data-search-form><span aria-hidden="true">⌕</span><input name="q" value="'+A.esc(value||"")+'" autocomplete="off" role="combobox" aria-autocomplete="list" aria-expanded="false" aria-label="検索"><button class="primary">検索</button><div class="suggestions" role="listbox" hidden></div></form>';}
function bindSearch(){const form=root.querySelector("[data-search-form]"),input=form.querySelector("input"),box=form.querySelector(".suggestions");form.addEventListener("submit",e=>{e.preventDefault();search(input.value,local.kind,"search");});input.addEventListener("input",()=>{const items=suggestions(input.value);box.innerHTML=items.map(x=>'<button type="button" role="option">'+A.esc(x)+'</button>').join("");box.hidden=!items.length;input.setAttribute("aria-expanded",String(items.length>0));box.querySelectorAll("button").forEach(b=>b.onclick=()=>{input.value=b.textContent;search(input.value,local.kind,"suggestion");});});input.addEventListener("keydown",e=>{const opts=[...box.querySelectorAll("button")];let i=opts.indexOf(document.activeElement);if(e.key==="ArrowDown"&&opts.length){e.preventDefault();opts[Math.min(i+1,opts.length-1)].focus();}});}
function renderHome(){persist({view:"home",sessionId:null});shell('<div class="search-home"><div class="brand-word">'+A.esc(A.brand.name)+'</div>'+searchBox("")+'<div class="toolbar"><button class="ghost" data-view="history">履歴</button><button class="ghost" data-view="about">この検索について</button></div></div>');bindSearch();root.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>renderView(b.dataset.view));}
function renderResults(results,suggestion,session){const tabs=["all","images","news"].map(k=>'<button class="ghost" data-kind="'+k+'" aria-selected="'+(local.kind===k)+'">'+({all:"すべて",images:"画像",news:"ニュース"}[k])+'</button>').join("");const rows=results.map(r=>'<article class="result '+(r.status==="deleted"?"deleted":"")+'"><div class="result-path">'+A.esc(r.path||r.url||"local")+'</div><h3><button class="nav-button" data-result="'+A.esc(r.id)+'">'+A.esc(r.title)+'</button></h3><p>'+A.esc(r.snippet||"")+'</p></article>').join("")||'<div class="empty"><div><h2>一致する結果はありません</h2><p>語句を変えるか、履歴を確認してください。</p></div></div>';const did=suggestion?'<p>もしかして: <button class="nav-button" data-suggest>'+A.esc(suggestion)+'</button></p>':"";shell('<div class="content"><div class="toolbar"><button class="icon-button" data-home aria-label="ホーム">⌂</button>'+searchBox(local.query)+'</div><div class="kind-tabs">'+tabs+'</div>'+did+'<div class="results-layout"><main><p class="muted">'+results.length+' 件・セッション '+A.esc(session.id)+'</p>'+rows+'</main><aside class="knowledge card"><h3>検索セッション</h3><p>'+A.esc(local.query)+'</p><button class="ghost" data-view="history">履歴を見る</button></aside></div></div>');bindSearch();root.querySelector("[data-home]").onclick=renderHome;root.querySelectorAll("[data-kind]").forEach(b=>b.onclick=()=>{local.kind=b.dataset.kind;search(local.query,local.kind,"kind");});root.querySelector("[data-suggest]")?.addEventListener("click",()=>search(suggestion,local.kind,"suggestion"));root.querySelector("[data-view]")?.addEventListener("click",()=>renderView("history"));root.querySelectorAll("[data-result]").forEach(b=>b.onclick=()=>openResult(results.find(x=>x.id===b.dataset.result),session));}
function openResult(item,session){if(!item)return;if(item.status==="deleted"||item.status==="404"){shell('<div class="browser-error"><h2>ページを表示できません</h2><p>索引には痕跡が残っていますが、本文は利用できません。</p><button class="primary" data-back>検索へ戻る</button></div>');root.querySelector("[data-back]").onclick=()=>restoreSession(session.id);return;}if(item.appId){A.openApp(item.appId,item.payload||{});return;}window.VDMEvidence.observe(item,"open-result");if(item.route){A.openApp("browser",{route:item.route,source:"search",sessionId:local.sessionId});}else if(item.media){window.VDMMedia.open(item.media);}else{shell('<div class="content"><button class="ghost" data-back>← 結果へ</button><article class="card knowledge"><h1>'+A.esc(item.title)+'</h1><p>'+A.esc(item.body||item.snippet||"")+'</p></article></div>');root.querySelector("[data-back]").onclick=()=>restoreSession(session.id);}}
function renderView(view){persist({view});if(view==="about"){shell('<div class="content"><button class="ghost" data-home>←</button><article class="card knowledge"><h1>この検索について</h1><p>'+A.esc(D.about||"ローカル索引です。")+'</p><h2>検索オプション</h2><p>NFKC正規化、空白・記号・ハイフン差、語順差を吸収します。</p></article></div>');root.querySelector("[data-home]").onclick=renderHome;return;}const rows=local.history.map(h=>'<div class="list-item history-row"><button class="nav-button" data-session="'+A.esc(h.sessionId)+'">'+A.esc(h.query)+'</button><small>'+new Date(h.at).toLocaleString("ja-JP")+' · '+A.esc(h.sessionId)+'</small></div>').join("")||'<div class="empty">検索履歴はありません</div>';shell('<div class="content"><button class="ghost" data-home>← ホーム</button><h1>検索履歴</h1><div class="list">'+rows+'</div></div>');root.querySelector("[data-home]").onclick=renderHome;root.querySelectorAll("[data-session]").forEach(b=>b.onclick=()=>restoreSession(b.dataset.session));}
const current=A.state?.get?.()||{};if(current.ending==="C"){const player=String(current.player?.displayName||"あなた").trim()||"あなた",at=new Date(current.endingAt||Date.now()).getTime(),endingSession={id:"ending-c-history",query:player,kind:"all",at,reason:"ending",resultIds:[],snapshot:[],worldVersion:current.worldVersion||9,pageVersion:current.pageVersion||0,suggestion:""};Object.assign(local,{view:"history",query:"",kind:"all",history:[{sessionId:endingSession.id,query:player,kind:"all",at,worldVersion:endingSession.worldVersion,pageVersion:endingSession.pageVersion}],sessions:[endingSession],sessionId:null});A.saveAppState(local);}
if(local.view==="results"&&local.sessionId)restoreSession(local.sessionId);else if(local.view==="results"&&local.query)search(local.query,local.kind,"reload-migration");else if(local.view==="history"||local.view==="about")renderView(local.view);else renderHome();
})();
